### PR TITLE
Just some front-end changes of text and some command aliasses

### PR DESCRIPTION
**Pull request by JustIanJ**

### CODE REVIEW

**Review by codeman1o1 — CHANGES_REQUESTED** [review]
Remove the aliases, these will most likely not be used and will decrease code readability

**Comment by JustIanJ** [comment]
Thank you for your hard work on TIJK-Bot

**Review by codeman1o1 — CHANGES_REQUESTED** [review]
Remove the change in line 204 and 219

**Review by codeman1o1 — CHANGES_REQUESTED** [review]
Undo the changes in line 403 and 433

**Pull request closed without merging**
